### ISSUE TITLE
please use the web browser to access a meeting 

### ISSUE THREAD

**Issue by days4** [bigbluebutton/bbb-air-client#58]
when i try bbb-air-client in pc its able to join a meeting .but when i created an apk and run it on android device it shows the error " please use the web browser to access a meeting ". Please help me to fix this. I am using test.blindsidenetworks.com for bbb server

**Comment by capilkey** [comment]
There are so many different front-ends for BBB that writing the authentication into the AIR app isn't feasible. In order to keep things simple the user must join the meeting through whatever front-end their organization uses. See the mobile.jsp demo for an example on how this is done.

It's not an issue with the product, but the intended functionality so I'm going to close this.
